project_id = "fzjeljgmsuyfqzbobokx"

[functions.bakong-qr]
verify_jwt = false

[functions.bakong-webhook]
verify_jwt = false

[functions.bakong-test]
verify_jwt = false

[functions.pterodactyl]
verify_jwt = false

[functions.invoice-generator]
verify_jwt = false

[functions.renewal-reminder]
verify_jwt = false

[functions.ikhode-payment]
verify_jwt = false
